name: livego_premium
version: 1.0.23+23
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  video_player: ^2.9.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  shared_preferences: ^2.3.2
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
