class PlatformRegistry {
  static const List<String> defaultPlatforms = [
    'freereels',
    'goodshort',
    'dramawave',
    'netshort',
    'reelshort',
    'melolo',
  ];

  static const List<String> supportedPlatforms = [
    'freereels',
    'goodshort',
    'dramawave',
    'netshort',
    'reelshort',
    'reelife',
    'rapidtv',
    'flickreels',
    'dramapops',
    'dramapoops',
    'shortmax',
    'dramanova',
    'dramarush',
    'melolo',
    'starshort',
    'meloshort',
    'dramabite',
    'stardusttv',
    'dramabox',
    'drachin',
    'youku',
    'tencent',
    'iqiyi',
    'mango',
    'wetv',
    'viki',
    'shorttv',
    'minidrama',
    'topreels',
    'moboreels',
    'flexreels',
    'livego',
  ];
}
